# -*- coding: 850 -*-
# -*- coding: utf-8 -*-

def getText(text,lang):
	if (lang == "es"):
		if text in libTextES:
			return libTextES[text]
		else:
			return text
	elif (lang == "en"):
		if text in libTextEN:
			return libTextEN[text]
		else:
			return text
	else:
		return text

libTextES = {
	"txt_00001":"INICIO",
	"txt_00002":"QUIENES SOMOS",
	"txt_00002-1":"Quienes Somos",
	"txt_00003":"GALERIA",
	"txt_00003-1":"Galería",
	"txt_00004":"SERVICIOS",
	"txt_00004-1":"COSTASUR",	
	"txt_00004-2":"SEGURIDAD",	
	"txt_00004-3":"BIENES RAICES",	
	"txt_00004-4":"COUNTRY CLUB",	
	"txt_00004-5":"HOTEL",	
	"txt_00005":"NOTICIAS",
	"txt_00005-1":"COSTASUR CASA DE CAMPO NEWS",
	"txt_00005-2":"Q' PASA EN CASA",
	"txt_00005-3":"CASA DE CAMPO LIVING",
	"txt_00006":"CONTACTOS",
	"txt_00007":"Mi Costasur",
	"txt_00008":"Menú",
	"txt_00009-1":"El hogar de sus sueños lo hacemos posible y está disponible para usted en Costasur Casa de Campo. Le ofrecemos una amplia variedad de opciones en nuestras atractivas, seguras y tranquilas áreas residenciales como son: Vista Lagos, Dye Fore, La Catalina, Los Flamboyanes, Golf Villas, Punta Aguila, Costa Mar, Punta Minitas, Chavón Vista y Las Palmas.",
	"txt_00009-2":"Contamos con la disponibilidad de solares donde puede construir su casa al estilo que siempre soñó. En Costasur tenemos nuestra propia planta generadora de energía, acueducto y el mejor serviccio de telecomunicaciones para garantizar la satisfacción de todas sus necesidades.",
	"txt_00009-3":"Adquiera una de nuestras propiedades y conviértase en un integrante más de nuestra gran familia en la comunidad Costasur Casa de Campo, el mejor lugar para vivir, invertir o vacacionar en el Complejo Turístico Inmobiliario más sólido del Caribe.",
	"txt_00010":"Servicios a Nuestra Comunidad",
	"txt_00011":"Agua Potable",	
	"txt_00011-1":"Contamos con nuestro propio acueducto y plantas de tratamiento, para suministrar agua potable a toda nuestra comunidad.",	
	"txt_00012":"Control de Mosquitos",
	"txt_00012-1":"Controlamos la propagación de larvas y mosquitos mediante nuestro programa de fumigación del entorno de nuestro complejo.",
	"txt_00013":"Servicio Al Cliente",
	"txt_00013-1":"Contamos con un personal altamente especializado, que atiende sus requerimientos las 24 horas del día, los 7 días la semana.",	
	"txt_00014-1":"Una empresa inmobiliaria y de servicios encargada de la comercialización, venta y administración de las propiedades y los servicios básicos en viviendas y negocios del exclusivo Complejo Turístico Casa de Campo, ubicado en La Romana, zona Este de la República Dominicana.",
	"txt_00014-2":"Casa de Campo es conocido como el principal y más completo Complejo Turístico de la Región del Caribe, con una privilegiada ubicación geográfica en el centro de América y cerca de las principales ciudades de la Costa Este de los Estados Unidos y Canadá (1 hr. 50 min. de Miami y 3 hr. de New York) y de la parte Norte de América del Sur (Caracas, Bogotá, entre otros).",
	"txt_00014-3":"Contamos con atractivos campos de golf como son los Links, Dye Fore y el más afamado en el Caribe Diente de Perro.",
	"txt_00014-4":"Estamos localizados a 10 minutos del Aeropuerto Internacional de La Romana,  a 50 minutos del Aeropuerto Internacional de Las Américas, en Santo Domingo, Capital de la República Dominicana, y 50 minutos del Aeropuerto Internacional de Punta Cana, todo esto a través de modernas carreteras.",
	"txt_00015":"Nos caracterizamos por ofrecer el más alto grado de calidad de los servicios, respondiendo a las necesidades de nuestros clientes con profesionalismo, seguridad y garantía, a la altura de las exigencias del mercado.",	
	"txt_00016":"Mantenimientos",
	"txt_00016-1":"Piscinas y Jacuzzi",
	"txt_00016-1-1":"Damos tratamiento y accesoría para mantener el agua de la piscina en estado natural y sin bacterias, limpieza y pintura de las paredes en piscina y jacuzzi.",
	"txt_00016-2":"Albañilería",
	"txt_00016-2-1":"Realizamos reparaciones y cambio de pisos, pañete, confección de aceras, caminos de jogging.",
	"txt_00016-3":"Carpintería",
	"txt_00016-3-1":"Trabajamos en todo tipo de madera, tabla de vista, balcón, piso, marco para puerta,  puertas, ventanas, bancos, mesa, silla, herrería y más.",
	"txt_00016-4":"Fumigación",
	"txt_00016-4-1":"Ofrecemos servicios de fumigación contra todos los insectos tanto al interior y al exterior de su hogar, áreas comunes, tratamiento para el comején.",
	"txt_00016-5":"Mantenimiento y suministro de calentadores de agua",
	"txt_00016-5-1":"Disponemos de personal para el suministro y mantenimiento  de calentadores de agua eléctricos y de gas propano, para piscinas, baños, cocinas y jacuzzi.",
	"txt_00016-6":"Reparación de Estufas",
	"txt_00016-6-1":"Brindamos el servicio de reparación y pintura de estufa, y admás, el suministro de todos los repuestos.",
	"txt_00016-7":"Pintura en general",
	"txt_00016-7-1":"Pintamos todo tipo de muros, techos, madera, pisos, puertas, ventanas, mobiliarios (silla, mesa, cama, bancos, etc.…)",
	"txt_00016-8":"Suministro de gas propano",
	"txt_00016-8-1":"Suministramos el gas propano en cilindros de 25, 50 y 100 lbs., también suministramos gas para los cilindros instalados en las villas, de 55 a 250 gls., hacemos reparaciones en las instalaciones.",
	"txt_00016-9":"Plomería en general",
	"txt_00016-9-1":"Reparamos todo tipo de roturas en tubería PVC y galvanizadas, reparamos grifos, llaves, detección y corrección de fuga de agua internas, cambio de lavamanos, inodoros y limpieza pozo séptico.",
	"txt_00016-10":"Mantenimiento de pisos",
	"txt_00016-10-1":"Este servicio trata de la limpieza, encerado y brillado de todo tipo de piso.",
	"txt_00017":"Eléctricos",
	"txt_00017-1":"Revisión de sistemas de medición",
	"txt_00017-1-1":"Garantizamos que los datos obtenidos de su medidor sean correctos, para tales fines contamos con equipos especializados en análisis de sistemas de medición.",
	"txt_00017-2":"Corrección de sistemas de aterrizaje",
	"txt_00017-2-1":"Se Verifica que la línea de puesta a tierra (línea de protección de circuitos eléctricos) se encuentre dentro de los parámetros establecidos por el Código Eléctrico Nacional (NEC), como medida preventiva de posibles daños a personas y  propiedades.",
	"txt_00017-3":"Instalación, reparación y mantenimiento de neveras y aires acondicionados",
	"txt_00017-3-1":"Revisión de equipos de refrigeración en general.",
	"txt_00017-3-2":"Alquiler de Neveras.",
	"txt_00017-3-3":"Instalación, reparación y mantenimiento de Aires Acondicionados.",
	"txt_00017-3-4":"Mantenimiento y reparación de neveras, vineras y cuartos fríos.",
	"txt_00017-3-5":"También contamos con los servicios de iguala para mantenimiento de dichos equipos.",
	"txt_00017-4":"Cambio de Breakers",
	"txt_00017-5":"Instalación y reparación de equipos eléctricos",
	"txt_00017-5-1":"Revisión eléctrica en general.",
	"txt_00017-5-2":"Alquiler de Bombas de Agua.",
	"txt_00017-5-3":"Instalación, cambio y mantenimiento de Abanicos.",
	"txt_00017-5-4":"Instalamos y reparamos: Bombas de agua para Jacuzzi, piscinas y  peceras.",
	"txt_00017-5-5":"Instalación  reparación y mantenimiento de lavadoras y secadoras.",
	"txt_00017-5-6":"Canalización para servicios de tele cable y teléfono.",
	"txt_00017-6":"Contamos con un departamento de Electromecánica, orientado a planificar, diseñar, calcular y dirigir todas las operaciones de construcción y mantenimiento de la infraestructura eléctrica. Además elaboramos los presupuestos operacionales y ofrecemos diversos servicios eléctricos al cliente, tanto de programación y coordinación de  todas las actividades de obras eléctricas.",
	"txt_00018":"Telecomunicaciones",
	"txt_00018-1":"Internet",
	"txt_00018-2":"Teléfono",
	"txt_00018-3":"Cable",
	"txt_00018-4":"Averías en General",
	"txt_00018-5":"Brindamos asistencia a los diferentes requerimientos de nuestros clientes (reclamaciones, reparaciones de averías eléctricas, plomería, ebanistería, teléfono, internet, cable, refrigeración, entre otras), dando solución a las problemáticas que puedan presentarse, de una manera ética, profesional y favorable; así como la venta de los servicios de internet, teléfono y cable, además de la información y guía efectiva de todos los servicios ofrecidos dentro del complejo Casa de Campo.",
	"txt_00018-6":"Servicios de Internet",
	"txt_00018-6-1":"Proveemos múltiples opciones para contratar servicios de Internet, con velocidades que van desde 1.0 Mbps hasta 100 Mbps, garantizando así, una experiencia óptima de navegación que se ajuste a las necesidades y expectativas de nuestros clientes.",
	"txt_00018-7":"Servicio Telefónico",
	"txt_00018-7-1":"Prestamos servicios de instalación y mantenimiento de líneas telefónicas, así por igual damos soporte a todo el sistema telefónico del Complejo, ofrecemos nuestro servicio de Call Center (Operador) que Trabaja 24/7, conectando nuestros clientes a todos los destinos nacionales e internacionales desde la comodidad de su hogar. Este servicio además posee la facilidad de llamadas ilimitadas dentro del complejo a través de extensiones sin ningún costo adicional, así como un servicio de asistencia ante emergencias (911) para comunicar nuestros clientes con los departamentos de asistencia ante situaciones de riesgo o necesidades particulares.",
	"txt_00018-8":"Servicios de Telecable",
	"txt_00018-8-1":"Nos aseguramos de que las propiedades tengan una amplia paleta de opciones de entretenimiento en cuanto a la televisión por cable se refiere, ofreciendo canales de vanguardia y una buena programación que incluye canales de alta definición, deportes, información y mucho más.",
	"txt_00018-9":"Desk de Averías",
	"txt_00018-9-1":"Brindamos soporte técnico a los servicios de  Internet, teléfono y Telecable, a través de nuestros agentes de servicios y técnicos especializados, e nuestras extensiones 2900 y 2902.",
	"txt_00019":"Legal Catastral",
	"txt_00019-1":"Deslindes",
	"txt_00019-2":"Sub-Divisiones",
	"txt_00019-3":"Refundiciones",
	"txt_00019-4":"Asesoría legal sobre terrenos",
	"txt_00019-5":"Servicios legales inmobiliarios y de agrimensura relacionados a los distintos procesos que se llevan ante todos los organismos que conforman la Jurisdicción Inmobiliaria de la República Dominicana, tales como la Dirección Nacional & Regional de  Mensuras Catastrales, Tribunales de Jurisdicción Original y Registro de Títulos, tales como deslindes, sub-divisiones, refundiciones y actualizaciones de parcelas, así como también traspasos y actualizaciones de Inmuebles ante la Dirección General de Impuestos Internos y el Registro de Títulos.",	
	"txt_00019-6":"Gestiones de certificaciones de propiedad inmobiliaria y de estado jurídico de inmuebles.",
	"txt_00020":"Cerrar",
	"txt_00021":"Contactos",
	"txt_00022":"Su requerimiento es importante para nosotros, favor contactarnos por alguna de las siguientes vías.",
	"txt_00023":"Servicio al Cliente",
	"txt_00024":"Operador",
	"txt_00025":"Síguenos en Twitter como",
	"txt_00026":"Siguenos en Facebook",
	"txt_00027":"Envianos un Correo a",
	"txt_00028":"Escríbenos",
	"txt_00029":"Nombre",
	"txt_00030":"E-mail",
	"txt_00031":"Requerimiento",
	"txt_00032":"Enviar",
	"txt_00033":"MAPA",
}

libTextEN = {
	"inicio":"HOME",
	"somos":"ABOUT",
	"mapa":"GALLERY",
	"productos":"SERVICES",
	"noticias":"NEWS",
	"contact":"CONTACTS",
	"desc_empresa":"Housing and service charge of marketing, sales and property management and housing complex Country House Company.",
	"serv_comu":"Service to Our Community",
	"agua":"Drinking water",
	"desc_agua":"We have our own water supply and treatment plants to supply drinking water to our community.",	
	"mosquito":"Mosquito Control",
	"desc_mosquito":"We control the spread of mosquito larvae and by our spraying program our complex environment.",
	"serv_cliente":"Customer Service",
	"desc_serv_cliente":"We have a dedicated staff to cater to your needs 24 hours a day, 7 days a week.",	
	"mant":"MAINTENANCE",
	"tele":"TELECOM",
	"legal":"CATASTRAL LEGAL",
	"bienes":"REAL ESTATE",
	"country":"COUNTRY CLUB",
	"hotel":"HOTEL",
	"cdcnews":"COSTASUR CASA DE CAMPO NEWS",
	"qpasa":"Q' PASA EN CASA",
	"cdl":"CASA DE CAMPO LIVING",
	"access":"SECURITY",
}


# libTextES = {
# 	"txt_00001":"Mi Costasur - Entrada",
# 	"txt_00002":"Iniciar Sesión",
# 	"txt_00003":"Correo Electrónico",
# 	"txt_00004":"Contraseña",
# 	"txt_00005":"Entrar",
# 	"txt_00006":"Español",
# 	"txt_00007":"English",
# 	"txt_00008":"",
# 	"txt_00009":"",
# 	"txt_00010":"",
# }

# libTextEN = {
# 	"txt_00001":"My Costasur - Login",
# 	"txt_00002":"Login",
# 	"txt_00003":"Email",
# 	"txt_00004":"Password",
# 	"txt_00005":"Enter",
# 	"txt_00006":"Español",
# 	"txt_00007":"English",
# 	"txt_00008":"",
# 	"txt_00009":"",
# 	"txt_00010":"",
# }